apiVersion: v1
kind: Service
metadata:
  name: ark
  namespace: heptio-ark
  labels:
    app: ark
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: metrics
      name: metrics
  selector:
    component: ark