apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: kube-prometheus
spec:
  allowPrivilegeEscalation: true
  privileged: true
  hostPID: true
  hostNetwork: true
  hostPorts:
  - min: 9100
    max: 9100
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
  - hostPath
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp-kube-prometheus
rules:
- apiGroups:
  - extensions
  resourceNames:
  - kube-prometheus
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-kube-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-kube-prometheus
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:monitoring
