replicaCount: 1

image:
  repository: {{BACKEND_REPO}}
  tag: latest
  pullPolicy: Always

url: https://backend.{{NAMESPACE}}.{{DNS_ZONE}}/

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-http01-ingress-class: nginx
  hosts:
    - host: backend.{{NAMESPACE}}.{{DNS_ZONE}}
      paths:
        - /
  tls:
    - secretName: backend-tls
      hosts:
        - backend.{{NAMESPACE}}.{{DNS_ZONE}}

mysqlHost: backend-{{NAMESPACE}}-mysql
mysqlRootPassword: {{MYSQL_ROOT_PASS}}
mysqlUser: {{MYSQL_USER}}
mysqlPassword: {{MYSQL_PASS}}
mysqlDatabase: {{MYSQL_DB}}

redisHost: backend-{{NAMESPACE}}-redis-master
redisPort: 6379
redisPass: {{REDIS_PASS}}

migrations:
  enabled: false

mysql:
  image: "mysql"
  imageTag: "5.7.25"
  mysqlRootPassword: {{MYSQL_ROOT_PASS}}
  mysqlUser: {{MYSQL_USER}}
  mysqlPassword: {{MYSQL_PASS}}
  mysqlDatabase: {{MYSQL_DB}}
  mysqlAllowEmptyPassword: false
  imagePullPolicy: IfNotPresent
  persistence:
    enabled: true
    storageClass: gp2-resize
    size: 8Gi
  metrics:
    enabled: true

phpmyadmin:
  db:
    host: backend-{{NAMESPACE}}-mysql
    port: 3306
  probesEnabled: false
  ingress:
    enabled: true
    annotations:
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      certmanager.k8s.io/acme-http01-ingress-class: nginx
    labels: {}
    host: pma.{{NAMESPACE}}.{{DNS_ZONE}}
    tls:
      - secretName: pma-general-tls
        hosts:
        - pma.{{NAMESPACE}}.{{DNS_ZONE}}

vin:
  replicaCount: 1
  image:
    repository: {{VIN_REPO}}
    tag: latest
    pullPolicy: Always
  mysqlHost: backend-{{NAMESPACE}}-mysql
  mysqlRootPassword: {{MYSQL_ROOT_PASS}}
  mysqlUser: {{MYSQL_USER}}
  mysqlPassword: {{MYSQL_PASS}}
  mysqlDatabase: {{MYSQL_DB}}
  smtpHost: email-smtp.us-east-1.amazonaws.com
  smtpPort: 587
  smtpFrom: vin_service@insurancetruck.com
  smtpTo: artem.z1@ironjab.com
  smtpName: {{SMTP_NAME}}
  smtpPassword: {{SMTP_PASS}}
  vinLink: https://vintelligence3.polk.com/vindecoder/VinDecoderService
  vinName: {{VIN_NAME}}
  vinPass: {{VIN_PASS}}
  mainSite: backend-{{NAMESPACE}}-it-backend
  mainPort: 80

aspire:
  replicaCount: 1
  image:
    repository: {{ASPIRE_REPO}}
    tag: latest
    pullPolicy: Always
  mysqlHost: backend-{{NAMESPACE}}-mysql
  mysqlRootPassword: {{MYSQL_ROOT_PASS}}
  mysqlUser: {{MYSQL_USER}}
  mysqlPassword: {{MYSQL_PASS}}
  mysqlDatabase: {{MYSQL_DB}}
  mainSite: backend-{{NAMESPACE}}-it-backend
  mainPort: 80
  smtpHost: email-smtp.us-east-1.amazonaws.com
  smtpPort: 587
  smtpFrom: vin_service@insurancetruck.com
  smtpTo1: artem.z1@ironjab.com
  smtpTo2: artem.z1@ironjab.com
  smtpName: {{SMTP_NAME}}
  smtpPassword: {{SMTP_PASS}}
  pushKey: {{PUSH_KEY}}
  pushLink: https://www.maple-tech.com/ctcstaging/services/createApp                            
  pushStatusLink: https://www.maple-tech.com/ctcstaging/services/quoteStatusQuery              
  pushMvrLink: https://www.maple-tech.com/ctcstaging/services/getMVR                           
  push: enabled 

redis:
  password: {{REDIS_PASS}}
  cluster:
    enabled: false
    slaveCount: 0
  master:
    persistence:
      enabled: true
      storageClass: gp2-resize
      size: 8Gi

