apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator-kube-etcd-main
    release: prometheus-operator
  name: prometheus-operator-kube-etcd-main
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: false
      caFile: /etc/prometheus/secrets/prometheus-operator-etcd/ca
      certFile: /etc/prometheus/secrets/prometheus-operator-etcd/cert
      keyFile: /etc/prometheus/secrets/prometheus-operator-etcd/key
      serverName: 127.0.0.1
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: prometheus-operator-kube-etcd-main
      release: prometheus-operator
  targetLabels:
  - type
