apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: drone
spec:
  secretName: drone-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: drone.{{DNS_ZONE}}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - drone.{{DNS_ZONE}}
