# Default values for it-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: {{REPO}}
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

url: https://it-backend.{{DNS_ZONE}}/

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - it-backend.{{DNS_ZONE}}
  tls:
    - secretName: it-backend-tls
      hosts:
        - it-backend.{{DNS_ZONE}}

nodeSelector: {}

tolerations: []

affinity: {}

xdebugHost: 192.168.0.100
xdebugPass: dev2016

mysqlHost: insurancetruck-db-mysql
mysqlRootPassword: {{MYSQL_ROOT_PASS}}
mysqlUser: {{MYSQL_USER}}
mysqlPassword: {{MYSQL_PASS}}
mysqlDatabase: {{MYSQL_DB}}

redisHost: it-backend-redis-master
redisPort: 6379
redisPass: {{REDIS_PASS}}

redis:
  password: {{REDIS_PASS}}
  cluster:
    enabled: false
    slaveCount: 0