apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  secretName: alertmanager-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: alertmanager.dimag.xyz
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - alertmanager.dimag.xyz
