apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: grafana
  namespace: monitoring
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: grafana.dimag.xyz
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - grafana.dimag.xyz
