apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: prometheus
  namespace: monitoring
spec:
  secretName: prometheus-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: prometheus.dimag.xyz
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - prometheus.dimag.xyz
