# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: {{REPO}}
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-http01-ingress-class: nginx
  hosts:
    - host: {{NAMESPACE}}.{{DNS_ZONE}}
      paths:
        - /
  tls:
    - secretName: frontend-tls
      hosts:
        - {{NAMESPACE}}.{{DNS_ZONE}}
