# Default values for it-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 784590408214.dkr.ecr.eu-central-1.amazonaws.com/insurancetruck/frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - it-frontend.example.com
  tls:
    - secretName: it-frontend-tls
      hosts:
        - it-frontend.example.com

nodeSelector: {}

tolerations: []

affinity: {}
