apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-operator-calico
    release: prometheus-operator
  name: prometheus-operator-calico
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    k8s-app: calico-node
  sessionAffinity: None
  type: ClusterIP
