apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-operator-kube-etcd-main
    jobLabel: kube-etcd-main
    release: prometheus-operator
    type: main
  name: prometheus-operator-kube-etcd-main
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 4001
    protocol: TCP
    targetPort: 4001
  selector:
    k8s-app: etcd-server
  sessionAffinity: None
  type: ClusterIP
