apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-operator-kube-etcd-events
    jobLabel: kube-etcd-events
    release: prometheus-operator
    type: events
  name: prometheus-operator-kube-etcd-events
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 4002
    protocol: TCP
    targetPort: 4002
  selector:
    k8s-app: etcd-manager-events
  sessionAffinity: None
  type: ClusterIP
