apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kibana
spec:
  secretName: kibana-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kibana.dimag.xyz
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - kibana.dimag.xyz
