apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: insurancetruck-dev-admins
  namespace: insurancetruck-dev
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: insurancetruck-dev-admins
  namespace: insurancetruck-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: insurancetruck-dev-admins
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: insurancetruck-dev-admins

# ---

# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: ClusterRoleBinding
# metadata:
#   name: developers-psp
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: default-psp
# subjects:
# - apiGroup: rbac.authorization.k8s.io
#   kind: Group
#   name: developers