apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cost-analyzer-checks
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cost-analyzer-checks
            image: ajaytripathy/kubecost-checks:prod-{{ $.Chart.Version }}
            args:
            - node
            - ./node/cron.js
            resources:
              requests:
                cpu: "20m"
                memory: "100Mi"
              limits:
                cpu: "100m"
                memory: "200Mi"
            env:
            - name: COST_ANALYZER_SERVER_ENDPOINT
              value: {{ template "cost-analyzer.fullname" . }}.{{ .Release.Namespace  }}.svc.cluster.local:9001
            - name: PROMETHEUS_ALERTMANAGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "cost-analyzer.fullname" . }}
                  key: prometheus-alertmanager-endpoint
          restartPolicy: OnFailure
