apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cost-analyzer.fullname" . }}
  labels:
    app: cost-analyzer
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  {{- if .Values.global.prometheus.enabled }}
    prometheus-alertmanager-endpoint: {{ .Values.global.notifications.alertmanager.fqdn }}
  {{- end -}}
  {{- if .Values.global.prometheus.enabled }}
    prometheus-server-endpoint: {{ .Values.global.prometheus.fqdn }}
  {{- end -}}
  {{- if .Values.kubecostToken }}
    kubecost-token: {{ .Values.kubecostToken }}
  {{ else }}
    kubecost-token: not-applied
  {{- end -}}