apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dex
  namespace: it-dev
spec:
  secretName: dex-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dex.{{DNS_ZONE}}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - dex.{{DNS_ZONE}}
