image: docker.io/dimag/dex
imageTag: "groups"
imagePullPolicy: "IfNotPresent"
config:
  issuer: https://dex.{{DNS_ZONE}}
  storage:
    type: kubernetes
    config:
      inCluster: true
  logger:
    level: info
  web:
    http: 0.0.0.0:8080
  grpc:
    addr: 0.0.0.0:5000
  connectors:
  - type: oidc
    id: auth0
    name: Auth0
    config: 
      issuer: {{AUTH0_DOMAIN}}
      clientID: {{AUTH0_CLIENT_ID}}
      clientSecret: {{AUTH0_CLIENT_SECRET}}
      redirectURI: https://dex.{{DNS_ZONE}}/callback
  oauth2:
    skipApprovalScreen: true
  staticClients:
  - name: 'Insurancetruck App'
    redirectURIs:
    - 'http://127.0.0.1:5555/callback'
    - 'https://oauth2.{{DNS_ZONE}}/oauth2/callback'
    id: {{DEX_ID}}
    secret: {{DEX_SECRET}}
  enablePasswordDB: false
ingress:
  enabled: true
  path: /
  hosts:
    - dex.{{DNS_ZONE}}
  tls:
    - secretName: dex-tls
      hosts:
        - dex.{{DNS_ZONE}}