# Default values for it-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: {{REPO}}
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - it-frontend.{{DNS_ZONE}}
  tls:
    - secretName: it-frontend-tls
      hosts:
        - it-frontend.{{DNS_ZONE}}

nodeSelector: {}

tolerations: []

affinity: {}
