apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vin.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vin.name" . }}
    helm.sh/chart: {{ include "vin.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vin.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vin.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "vin.fullname" . }}
                key: mysqlRootPassword
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: {{ include "vin.fullname" . }}
                key: mysqlHost
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "vin.fullname" . }}
                key: mysqlUser
          - name: MYSQL_PASS
            valueFrom:
              secretKeyRef:
                name: {{ include "vin.fullname" . }}
                key: mysqlPass
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ include "vin.fullname" . }}
                key: dbName
          - name: SMTP_HOST
            value: {{ .Values.smtpHost }}
          - name: SMTP_PORT
            value: "{{ .Values.smtpPort }}"
          - name: SMTP_FROM
            value: {{ .Values.smtpFrom }}
          - name: SMTP_TO
            value: {{ .Values.smtpTo }}
          - name: SMTP_NAME
            valueFrom:
              secretKeyRef:
                name: {{ include "vin.fullname" . }}
                key: smtpName
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "vin.fullname" . }}
                key: smtpPassword
          - name: VIN_LINK
            value: {{ .Values.vinLink }}
          - name: VIN_NAME
            valueFrom:
              secretKeyRef:
                name: {{ include "vin.fullname" . }}
                key: vinName
          - name: VIN_PASS
            valueFrom:
              secretKeyRef:
                name: {{ include "vin.fullname" . }}
                key: vinPass
          - name: MAIN_SITE
            value: {{ .Values.mainSite }}
          - name: MAIN_PORT
            value: "{{ .Values.mainPort }}"
      restartPolicy: Always