apiVersion: v1
kind: Secret
metadata:
  name: {{ template "it-vin.fullname" . }}-secrets
  labels:
    app: {{ template "it-vin.name" . }}
    chart: {{ template "it-vin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  mysqlHost: "{{ .Values.mysqlHost | b64enc }}"
  mysqlRootPassword: "{{ .Values.mysqlRootPassword | b64enc }}"
  mysqlUser: "{{ .Values.mysqlUser | b64enc }}"
  mysqlPass: "{{ .Values.mysqlPassword | b64enc }}"
  dbName: "{{ .Values.mysqlDatabase | b64enc }}"
  smtpName: "{{ .Values.smtpName | b64enc }}"
  smtpPassword: "{{ .Values.smtpPassword | b64enc }}"
  vinName: "{{ .Values.vinName | b64enc }}"
  vinPass: "{{ .Values.vinPass | b64enc }}"