apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: oauth2
spec:
  secretName: oauth2-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: oauth2.{{DNS_ZONE}}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - oauth2.{{DNS_ZONE}}
