kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dex.{{DNS_ZONE}}#{{AUTH0_USER_USERNAME}}
subjects:
- kind: User
  name: https://dex.{{DNS_ZONE}}#{{AUTH0_USER_USERNAME}}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
