apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: {{.name}}.{{.dnsZone}}
spec:
  kubeDNS:
    provider: CoreDNS
  kubelet:
    resolvConf: /run/systemd/resolve/resolv.conf
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "sts:AssumeRole"
          ],
          "Resource": [
            "arn:aws:iam::{{.awsAccountID}}:role/k8s-*"
          ]
        }
      ]
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://{{.s3bucket}}/{{.name}}.{{.dnsZone}}
  dnsZone: {{.dnsZone}}
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-{{.awsRegion}}a
      name: a
      volumeSize: {{.etcdVolumeSize}}
{{if .multiMaster}}
    - instanceGroup: master-{{.awsRegion}}b
      name: b
      volumeSize: {{.etcdVolumeSize}}
    - instanceGroup: master-{{.awsRegion}}c
      name: c
      volumeSize: {{.etcdVolumeSize}}
{{end}}
    name: main
    version: 3.2.24
  - etcdMembers:
    - instanceGroup: master-{{.awsRegion}}a
      name: a
      volumeSize: {{.etcdEventsVolumeSize}}
{{if .multiMaster}}
    - instanceGroup: master-{{.awsRegion}}b
      name: b
      volumeSize: {{.etcdEventsVolumeSize}}
    - instanceGroup: master-{{.awsRegion}}c
      name: c
      volumeSize: {{.etcdEventsVolumeSize}}
{{end}}
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditLogFormat: json
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditPolicyFile: /srv/kubernetes/audit.yaml
    authorizationMode: Node,RBAC
    enableAdmissionPlugins:
    # - DenyEscalatingExec
    # - PodSecurityPolicy
    - Initializers
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    - PersistentVolumeClaimResize
    - AlwaysPullImages
    - Priority
    anonymousAuth: false
    featureGates:
      ExpandPersistentVolumes: "true"
    oidcClientID: kubernetes
    oidcIssuerURL: https://keycloak.{{.dnsZone}}/auth/realms/{{.name}}
    oidcUsernameClaim: name
    oidcGroupsClaim: groups
  kubeControllerManager:
    featureGates:
      ExpandPersistentVolumes: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.7
  masterInternalName: api.internal.{{.name}}.{{.dnsZone}}
  masterPublicName: api.{{.name}}.{{.dnsZone}}
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: {{.awsRegion}}a
    type: Public
    zone: {{.awsRegion}}a
  - cidr: 172.20.64.0/19
    name: {{.awsRegion}}b
    type: Public
    zone: {{.awsRegion}}b
  - cidr: 172.20.96.0/19
    name: {{.awsRegion}}c
    type: Public
    zone: {{.awsRegion}}c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
  fileAssets:
    - name: audit.yaml
      path: /srv/kubernetes/audit.yaml
      roles: [Master]
      content: |
        apiVersion: audit.k8s.io/v1beta1 # This is required.
        kind: Policy
        omitStages:
          - "RequestReceived"
        rules:
          - level: RequestResponse
            resources:
            - group: ""
              resources: ["pods"]
          - level: Metadata
            resources:
            - group: ""
              resources: ["pods/log", "pods/status"]
          - level: None
            resources:
            - group: ""
              resources: ["configmaps"]
              resourceNames: ["controller-leader"]
          - level: None
            users: ["system:kube-proxy"]
            verbs: ["watch"]
            resources:
            - group: "" # core API group
              resources: ["endpoints", "services"]
          - level: None
            userGroups: ["system:authenticated"]
            nonResourceURLs:
            - "/api*" # Wildcard matching.
            - "/version"
          - level: Request
            resources:
            - group: "" # core API group
              resources: ["configmaps"]
            namespaces: ["kube-system"]
          - level: Metadata
            resources:
            - group: "" # core API group
              resources: ["secrets", "configmaps"]
          - level: Request
            resources:
            - group: "" # core API group
            - group: "extensions" # Version of group should NOT be included.
          - level: Metadata
            omitStages:
              - "RequestReceived"

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{.name}}.{{.dnsZone}}
  name: master-{{.awsRegion}}a
spec:
  image: {{.masterImage}}
  machineType: {{.masterMachineType}}
  maxSize: {{.masterMaxSize}}
  minSize: {{.masterMinSize}}
  nodeLabels:
    kops.k8s.io/instancegroup: master-{{.awsRegion}}a
  role: Master
  rootVolumeSize: {{.masterRootVolumeSize}}
  subnets:
  - {{.awsRegion}}a

{{if .multiMaster}}
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{.name}}.{{.dnsZone}}
  name: master-{{.awsRegion}}b
spec:
  image: {{.masterImage}}
  machineType: {{.masterMachineType}}
  maxSize: {{.masterMaxSize}}
  minSize: {{.masterMinSize}}
  nodeLabels:
    kops.k8s.io/instancegroup: master-{{.awsRegion}}b
  role: Master
  rootVolumeSize: {{.masterRootVolumeSize}}
  subnets:
  - {{.awsRegion}}b

{{end}}
{{if .multiMaster}}
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{.name}}.{{.dnsZone}}
  name: master-{{.awsRegion}}c
spec:
  image: {{.masterImage}}
  machineType: {{.masterMachineType}}
  maxSize: {{.masterMaxSize}}
  minSize: {{.masterMinSize}}
  nodeLabels:
    kops.k8s.io/instancegroup: master-{{.awsRegion}}c
  role: Master
  rootVolumeSize: {{.masterRootVolumeSize}}
  subnets:
  - {{.awsRegion}}c

{{end}}
---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{.name}}.{{.dnsZone}}
  name: nodes-{{.awsRegion}}a
spec:
  image: {{.nodeImage}}
  machineType: {{.nodeMachineType}}
  maxSize: {{.nodeMaxSize}}
  minSize: {{.nodeMixSize}}
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-{{.awsRegion}}a
  role: Node
  rootVolumeSize: {{.nodeRootVolumeSize}}
  subnets:
  - {{.awsRegion}}a
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kubernetes.io/cluster/{{.name}}.{{.dnsZone}}: ""

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{.name}}.{{.dnsZone}}
  name: nodes-{{.awsRegion}}b
spec:
  image: {{.nodeImage}}
  machineType: {{.nodeMachineType}}
  maxSize: {{.nodeMaxSize}}
  minSize: {{.nodeMixSize}}
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-{{.awsRegion}}b
  role: Node
  rootVolumeSize: {{.nodeRootVolumeSize}}
  subnets:
  - {{.awsRegion}}b
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kubernetes.io/cluster/{{.name}}.{{.dnsZone}}: ""

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{.name}}.{{.dnsZone}}
  name: nodes-{{.awsRegion}}c
spec:
  image: {{.nodeImage}}
  machineType: {{.nodeMachineType}}
  maxSize: {{.nodeMaxSize}}
  minSize: {{.nodeMixSize}}
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-{{.awsRegion}}c
  role: Node
  rootVolumeSize: {{.nodeRootVolumeSize}}
  subnets:
  - {{.awsRegion}}c
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kubernetes.io/cluster/{{.name}}.{{.dnsZone}}: ""

---

apiVersion: kops/v1alpha2
kind: SSHCredential
metadata:
  labels:
    kops.k8s.io/cluster: {{.name}}.{{.dnsZone}}
spec:
  publicKey: {{.publicKey}}
