name: cluster1
dnsZone: k8s.ironjab.com
awsAccountID: "532715861419" # aws sts get-caller-identity --output text --query 'Account'
awsRegion: us-east-1
s3bucket: ironjab-k8s-ss
etcdVolumeSize: 10
etcdEventsVolumeSize: 10
# k8s masters ig
masterImage: ami-0a313d6098716f372
masterMachineType: t2.medium
multiMaster: true
masterMaxSize: 1
masterMinSize: 1 # multiMaster = true => 1 * 3 subnets = 3 nodes; multiMaster = false => 1 * 1 subnet = 1 node
masterRootVolumeSize: 50
# k8s nodes ig
nodeImage: ami-0a313d6098716f372
nodeMachineType: t2.medium
nodeMaxSize: 3
nodeMixSize: 1 # 1 * 3 subnets = 3 nodes
nodeRootVolumeSize: 50
# jenkins slaves ig
spotImage: ami-0a313d6098716f372
spotMachineType: t3.small
spotMaxPrice: "0.01"
spotMaxSize: 10
spotMinSize: 1
# cluster ssh public key
publicKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7xqw5xMZt+WsMczrXJ3YERmkcCXGFOuEytc+zkCS336umPMtwxpOrHYS2SglWbwsRHAZvHfYRcN19pXf3TV836oxsi0I6C4ARi64Gn3EQupdQ2w8okx8bdjxzeeYInLbbb9Qus7AwMMlu+ruJsOkkOhaVaDfvFmrTND5DjegRYvBsHHx1dlGvK4zZnbed8bB1lxpmevGmDsQjqYKZiyV8Ns6GwJMq5IbOPktoSbJ+LrCUzsAW/4caDKO9EHvK6aPza+DZaRQa6lJ9H9NybFPJMWHC3KHq7MiF3GQLCqUNaKe+s7SVF0lT0eKKYmvTLWHJY43cl6BlYRI8Mc5HjXe9 dimag@xps
